
class Video():
    pass

#MÉTODOS BÁSICOS:

#SEGREGAR POR ESCENA.
    #ANALISIS DE ESCENA: LOCACIÓN
        #SUPERFICIE  --> SUELO Y ENTORNO

#SEGREGAR POR PLANO.

#MÉTODOS COMPLEJOS: MUY DIFÍCILES, PERO AYUDARÍAN A AUTOMATIZAR CASI COMPLETAMENTE
#EL PROCESO DE EDICIÓN DE SONIDO. UN PRIMER PASO SERÍA CREAR UN WIDGET PARA
#ANALISIS DE VIDEO SEMI-AUTOMATIZADO O DIRECTAMENTE POR USUARIO HUMANO.

#CREAR PLANTA DE ESCENA

#RECONOCER PERONAJES: CREAR PERFIL. ROPA Y CALZADO. TIPO DE VOZ (RELACIONAR CON
                    # AUDIO)
                    #UBICACIÓN ESPACIAL Y MOVIMIENTOS.
                    #ACCIONES


